#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/home/$damuid/go/bin/dam-client"
pidfile="/var/run/dam-client.pid"

description="Tor DAM client"

depend() {
	after tor dam-dir
}

start() {
	start-stop-daemon --start --background -u $damuid -g $damgid \
		--make-pidfile --pidfile $pidfile \
		--startas /bin/sh -- -c "exec $command >> $damlog 2>&1"
}
